name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Run manually from GitHub UI

jobs:
  test:
    runs-on: self-hosted  # This runs on your own machine
    steps:
      - name: Check runner is working
        run: echo "🎉 Self-hosted runner is working!"
